server:
  host: 0.0.0.0
  port: 4000

authenticator:
  # Pass
database:
  database_addr: 127.0.0.1:9042
  keyspace: concert_connect
  tables:
    user_table:
      name: user_table
      columns:
        - name: user_uuid
          dtype: uuid
        - name: first_name
          dtype: text
        - name: last_name
          dtype: text
        - name: email
          dtype: text
        - name: active
          dtype: boolean
        - name: paused
          dtype: boolean
        - name: sign_up_date
          dtype: timestamp
      primary_key: user_uuid
    claimed_pass_table:
      name: claimed_passes
      columns:
        - name: ticket_uuid
          dtype: uuid
        - name: concert_uuid
          dtype: uuid
        - name: user_uuid
          dtype: uuid
        - name: venue_uuid
          dtype: uuid
        - name: concert_date
          dtype: timestamp
        - name: venue_name
          dtype: text
        - name: artist_name
          dtype: text
        - name: standby
          dtype: boolean
      primary_key: user_uuid, ticket_uuid, concert_uuid
    unclaimed_pass_table:
      name: unclaimed_passes
      columns:
        - name: ticket_uuid
          dtype: uuid
        - name: concert_uuid
          dtype: uuid
        - name: venue_uuid
          dtype: uuid
        - name: concert_date
          dtype: timestamp
        - name: venue_name
          dtype: text
        - name: artist_name
          dtype: text
        - name: standby
          dtype: boolean
      primary_key: concert_uuid, ticket_uuid
    concert_table:
      name: concert_table
      columns:
        - name: concert_uuid
          dtype: uuid
        - name: venue_uuid
          dtype: uuid
        - name: concert_date
          dtype: timestamp
        - name: artist_name
          dtype: text
        - name: artist_bio
          dtype: text
        - name: artist_image
          dtype: text
        - name: artist_video
          dtype: text
        - name: standby_tickets
          dtype: int
        - name: secured_tickets
          dtype: int
      primary_key: concert_uuid
    venue_table:
      name: venue_table
      columns:
        - name: venue_uuid
          dtype: uuid
        - name: name
          dtype: text
        - name: address
          dtype: text
        - name: capacity
          dtype: int
      primary_key: venue_uuid


